=== estebanroblesluna/webspec-language/modules/webspeclanguage-metamock-core/src/test/resources/org/webspeclanguage/metamock/io/metamock.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.webspeclanguage.org/metamock"
  targetNamespace="http://www.webspeclanguage.org/metamock">

  <element name="mockups" type="tns:tMockups" />

  <complexType name="tMockups">
    <sequence minOccurs="0" maxOccurs="unbounded">
      <element ref="tns:ui" />
    </sequence>
    <attribute name="containerName" />
  </complexType>

  <!-- WIDGET -->
  <element name="widget" type="tns:tWidget" abstract="true" />

  <complexType name="tWidget">
    <sequence minOccurs="0" maxOccurs="1">
      <element ref="tns:layoutInfo" />
    </sequence>
    <attribute name="id" type="string" use="required" />
    <attribute name="friendlyId" type="string" />
  </complexType>

  <element name="layoutInfo">
    <complexType>
      <sequence>
        <element ref="tns:abstractLayoutInfo" />
      </sequence>
    </complexType>
  </element>

  <element name="labeledWidget" type="tns:tLabeledWidget"
    substitutionGroup="tns:widget" abstract="true" />

  <complexType name="tLabeledWidget">
    <complexContent>
      <extension base="tns:tWidget">
        <attribute name="label" type="string" />
      </extension>
    </complexContent>
  </complexType>

  <element name="button" type="tns:tButton" substitutionGroup="tns:labeledWidget" />

  <complexType name="tButton">
    <complexContent>
      <extension base="tns:tLabeledWidget"></extension>
    </complexContent>
  </complexType>

  <element name="label" type="tns:tLabel" substitutionGroup="tns:labeledWidget" />

  <complexType name="tLabel">
    <complexContent>
      <extension base="tns:tLabeledWidget"></extension>
    </complexContent>
  </complexType>

  <element name="checkbox" type="tns:tCheckbox"
    substitutionGroup="tns:labeledWidget" />

  <complexType name="tCheckbox">
    <complexContent>
      <extension base="tns:tLabeledWidget"></extension>
    </complexContent>
  </complexType>

  <element name="radioButton" type="tns:tRadioButton"
    substitutionGroup="tns:labeledWidget" />

  <complexType name="tRadioButton">
    <complexContent>
      <extension base="tns:tLabeledWidget"></extension>
    </complexContent>
  </complexType>

  <element name="textBox" type="tns:tTextBox" substitutionGroup="tns:widget" />

  <complexType name="tTextBox">
    <complexContent>
      <extension base="tns:tWidget" />
    </complexContent>
  </complexType>

  <!-- COMPOSITE WIDGET -->
  <element name="compositeWidget" type="tns:tCompositeWidget"
    abstract="true" substitutionGroup="tns:widget" />

  <complexType name="tCompositeWidget">
    <complexContent>
      <extension base="tns:tWidget">
        <sequence>
          <sequence>
            <element ref="tns:layout" />
          </sequence>
          <sequence minOccurs="0" maxOccurs="unbounded">
            <element ref="tns:widget" />
          </sequence>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <element name="layout">
    <complexType>
      <sequence>
        <element ref="tns:abstractLayout" />
      </sequence>
    </complexType>
  </element>

  <element name="ui" type="tns:tUi" substitutionGroup="tns:compositeWidget" />

  <complexType name="tUi">
    <complexContent>
      <extension base="tns:tCompositeWidget">
        <attribute name="title" type="string" use="required" />
      </extension>
    </complexContent>
  </complexType>

  <element name="panel" type="tns:tPanel" substitutionGroup="tns:compositeWidget" />

  <complexType name="tPanel">
    <complexContent>
      <extension base="tns:tCompositeWidget" />
    </complexContent>
  </complexType>

  <!-- LAYOUT -->
  <element name="abstractLayout" type="tns:tLayout" abstract="true" />

  <complexType name="tLayout">

  </complexType>

  <element name="flowLayout" type="tns:tFlowLayout"
    substitutionGroup="tns:abstractLayout" />

  <complexType name="tFlowLayout">
    <complexContent>
      <extension base="tns:tLayout" />
    </complexContent>
  </complexType>

  <element name="linealLayout" type="tns:tLinealLayout"
    substitutionGroup="tns:abstractLayout" />

  <complexType name="tLinealLayout">
    <complexContent>
      <extension base="tns:tLayout">
        <attribute name="type">
          <simpleType>
            <restriction base="string">
              <enumeration value="vertical" />
              <enumeration value="horizontal" />
            </restriction>
          </simpleType>
        </attribute>
        <attribute name="boxes" type="integer" />
      </extension>
    </complexContent>
  </complexType>

  <element name="gridBagLayout" type="tns:tGridBagLayout"
    substitutionGroup="tns:abstractLayout" />

  <complexType name="tGridBagLayout">
    <complexContent>
      <extension base="tns:tLayout">
        <attribute name="columns" type="integer" use="required" />
        <attribute name="rows" type="integer" use="required" />
      </extension>
    </complexContent>
  </complexType>

  <!-- LAYOUT INFO -->
  <element name="abstractLayoutInfo" type="tns:tLayoutInfo"
    abstract="true" />

  <complexType name="tLayoutInfo">

  </complexType>

  <element name="linealLayoutInfo" type="tns:tLinealLayoutInfo"
    substitutionGroup="tns:abstractLayoutInfo" />

  <complexType name="tLinealLayoutInfo">
    <complexContent>
      <extension base="tns:tLayoutInfo">
        <attribute name="box" type="integer" use="required" />
      </extension>
    </complexContent>
  </complexType>

  <element name="gridBoxLayoutInfo" type="tns:tGridBoxLayoutInfo"
    substitutionGroup="tns:abstractLayoutInfo" />

  <complexType name="tGridBoxLayoutInfo">
    <complexContent>
      <extension base="tns:tLayoutInfo">
        <attribute name="column" type="integer" use="required" />
        <attribute name="row" type="integer" use="required" />
        <attribute name="colspan" type="integer" default="1" />
        <attribute name="rowspan" type="integer" default="1" />
      </extension>
    </complexContent>
  </complexType>

</schema>

=== estebanroblesluna/webspec-language/modules/webspeclanguage-metamock-core/src/test/java/org/webspeclanguage/metamock/io/metamock.xml
<mockups xmlns="http://www.webspeclanguage.org/metamock"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.webspeclanguage.org/metamock metamock.xsd ">
  <ui title="Login screen" id="loginScreen">
    <layout>
      <flowLayout />
    </layout>
    <button id="loginButton" label="Login" />
    <label id="usernameLabel" label="Username: " />
    <textBox id="usernameTextbox" />
    <label id="passwordLabel" label="Password: " />
    <textBox id="passwordTextbox" />
    <button id="loginButton" label="Login"/>
    <checkbox id="rememberMeCheckbox" label="Remember me on this computer"/>
  </ui>
</mockups>
