=== estebanroblesluna/webspec-language/trunk/modules/webspeclanguage-io/src/main/resources/webspec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:tns="http://www.webspeclanguage.org/webspec" 
  targetNamespace="http://www.webspeclanguage.org/webspec">
    
    <!-- DIAGRAMS -->
    <element name="diagram" type="tns:tDiagram"/>
    
    <complexType name="tDiagram">
      <choice minOccurs="0" maxOccurs="unbounded" >
        <element ref="tns:interaction"/>
        <element ref="tns:transition"/>
        <element ref="tns:generator"/>
      </choice>
      <attribute name="name" type="string"/>
    </complexType>
    
    <!-- INTERACTIONS -->
    <element name="interaction" type="tns:tInteraction"/>
    
    <complexType name="tInteraction">
      <sequence minOccurs="0" maxOccurs="unbounded" >
        <element ref="tns:widget"/>
      </sequence>
      <attribute name="name" type="string"/>
      <attribute name="starting" type="boolean" default="false"/>
      <attribute name="invariant" type="string"/>
    </complexType>

    <!-- TRANSITIONS -->
    <element name="transition" type="tns:tTransition" abstract="true"/>

    <complexType name="tTransition">
      <attribute name="from" type="string"></attribute>
      <attribute name="to" type="string"></attribute>
      <attribute name="precondition" type="string"></attribute>
      <attribute name="actions" type="string"></attribute>
    </complexType>

    <element name="navigation" type="tns:tNavigation" substitutionGroup="tns:transition"/>

    <complexType name="tNavigation">
      <complexContent>
        <extension base="tns:tTransition"></extension>
      </complexContent>
    </complexType>

    <element name="rich-behavior" type="tns:tRichBehavior" substitutionGroup="tns:transition"/>

    <complexType name="tRichBehavior">
      <complexContent>
        <extension base="tns:tTransition"></extension>
      </complexContent>
    </complexType>



    <!-- GENERATORS -->
    <element name="generator" type="tns:tGenerator" abstract="true"/>
    
    <complexType name="tGenerator">
      <attribute name="name" type="string"/>
    </complexType>

    <element name="boolean-generator" type="tns:tBooleanGenerator" substitutionGroup="tns:generator"/>
    
    <complexType name="tBooleanGenerator">
      <complexContent>
        <extension base="tns:tGenerator"></extension>
      </complexContent>
    </complexType>

    <element name="one-of-array-generator" type="tns:tOneOfArrayGenerator" substitutionGroup="tns:generator"/>

    <complexType name="tOneOfArrayGenerator">
      <complexContent>
        <extension base="tns:tGenerator"></extension>
      </complexContent>
    </complexType>

    <element name="one-of-number-generator" type="tns:tOneOfNumberGenerator" substitutionGroup="tns:generator"/>

    <complexType name="tOneOfNumberGenerator">
      <complexContent>
        <extension base="tns:tGenerator"></extension>
      </complexContent>
    </complexType>

    <element name="one-of-string-generator" type="tns:tOneOfStringGenerator" substitutionGroup="tns:generator"/>

    <complexType name="tOneOfStringGenerator">
      <complexContent>
        <extension base="tns:tGenerator">
          <attribute name="values" type="string"/>
        </extension>
      </complexContent>
    </complexType>
    
    <element name="string-generator" type="tns:tStringGenerator" substitutionGroup="tns:generator"/>

    <complexType name="tStringGenerator">
      <complexContent>
        <extension base="tns:tGenerator"></extension>
      </complexContent>
    </complexType>

    <element name="uniform-number-generator" type="tns:tUniformNumberGenerator" substitutionGroup="tns:generator"/>

    <complexType name="tUniformNumberGenerator">
      <complexContent>
        <extension base="tns:tGenerator"></extension>
      </complexContent>
    </complexType>



    <!-- WIDGETS -->
    <element name="widget" type="tns:tWidget" abstract="true"/>

    <complexType name="tWidget">
      <attribute name="name" type="string"></attribute>
      <attribute name="location" type="string"></attribute>
    </complexType>

    <element name="button" type="tns:tButton" substitutionGroup="tns:widget"/>

    <complexType name="tButton">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>

    <element name="checkbox" type="tns:tCheckBox" substitutionGroup="tns:widget"/>

    <complexType name="tCheckBox">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>

    <element name="combobox" type="tns:tComboBox" substitutionGroup="tns:widget"/>

    <complexType name="tComboBox">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>

    <element name="label" type="tns:tLabel" substitutionGroup="tns:widget"/>

    <complexType name="tLabel">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>

    <element name="link" type="tns:tLink" substitutionGroup="tns:widget"/>

    <complexType name="tLink">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>

    <element name="listbox" type="tns:tListBox" substitutionGroup="tns:widget"/>

    <complexType name="tListBox">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>
    
    <element name="radiobutton" type="tns:tRadioButton" substitutionGroup="tns:widget"/>

    <complexType name="tRadioButton">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>
    
    <element name="textfield" type="tns:tTextField" substitutionGroup="tns:widget"/>

    <complexType name="tTextField">
      <complexContent>
        <extension base="tns:tWidget"></extension>
      </complexContent>
    </complexType>

    <!-- WIDGETS - CONTAINERS -->
    <complexType name="tContainer">
      <complexContent>
        <extension base="tns:tWidget">
          <sequence minOccurs="0" maxOccurs="unbounded" >
            <element ref="tns:widget"/>
          </sequence>
        </extension>
      </complexContent>
    </complexType>

    <element name="list-of" type="tns:tListOf" substitutionGroup="tns:widget"/>

    <complexType name="tListOf">
      <complexContent>
        <extension base="tns:tContainer"></extension>
      </complexContent>
    </complexType>

    <element name="panel" type="tns:tPanel" substitutionGroup="tns:widget"/>

    <complexType name="tPanel">
      <complexContent>
        <extension base="tns:tContainer"></extension>
      </complexContent>
    </complexType>
</schema>

=== estebanroblesluna/webspec-language/modules/webspeclanguage-io/src/test/resources/webspecexample.xml
<diagram 
  xmlns="http://www.webspeclanguage.org/webspec" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.webspeclanguage.org/webspec webspec.xsd"
  name="example">

  <one-of-string-generator name="products" values="hello,how,are,you" />
  
  <interaction name="Home" starting="true">
    <button name="search" />
    <textfield name="searchTF" />
  </interaction>

  <interaction name="SearchResults" invariant="searchTitle.text = ${productName}">
    <label name="searchTitle" />
    <list-of name="books">
      <label name="price" />
    </list-of>
  </interaction>

  <navigation from="Home" to="SearchResults" actions="productName := $products$; type(Home.searchTF, ${productName}); click(Home.search)" />
  
  <rich-behavior from="Home" to="SearchResults" actions="click(Home.search)" />
</diagram>

=== estebanroblesluna/webspec-language/modules/webspeclanguage-test-selenium/src/test/resources/org/webspeclanguage/webtest/generator/selenium/java/SeleniumJavaWebTestGeneratorIntegrationTestCase.testWebTestIOExampleGeneration.xml
<diagram name="LoginAsUser"
  xmlns="http://www.webspeclanguage.org/webspec" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.webspeclanguage.org/webspec webspec.xsd">
 
  <one-of-strings-generator name="usernames" values="esteban" />
  
  <interaction name="Login" starting="true" location="http://localhost:8080">
    <textfield name="username" />
    <textfield name="password" />
    <button name="login" />
  </interaction>

  <interaction name="Home" invariant="Home.message.text = 'Hello ' # ${username}">
    <label name="message" />
  </interaction>

  <navigation from="Login" to="Home" actions="username := $usernames$; type(Login.username, ${username}); type(Login.password, 'hi'); click(Login.login)" />
</diagram>
