=== estebanroblesluna/webspec-language/modules/webspeclanguage-mockupdd-io/src/test/resources/org/webspeclanguage/metamock/io/sui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.webspeclanguage.org/sui"
	targetNamespace="http://www.webspeclanguage.org/sui">

	<element name="mockups" type="tns:tMockups" />

	<complexType name="tMockups">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:ui" />
		</sequence>
		<attribute name="containerName" />
	</complexType>

	<!-- WIDGET -->
	<element name="widget" type="tns:tWidget" abstract="true" />

	<complexType name="tWidget">
		<sequence>
			<sequence minOccurs="0" maxOccurs="1">
				<element ref="tns:layoutInfo" />
			</sequence>
			<sequence minOccurs="0" maxOccurs="1">
				<element ref="tns:originalPosition" />
			</sequence>
			<sequence minOccurs="0" maxOccurs="1">
				<element ref="tns:tags" />
			</sequence>
		</sequence>
		<attribute name="id" type="string" use="required" />
		<attribute name="friendlyId" type="string" />
	</complexType>

	<element name="originalPosition" type="tns:tOriginalPosition" />

	<complexType name="tOriginalPosition">
		<attribute name="x" type="integer" use="required" />
		<attribute name="y" type="integer" use="required" />
		<attribute name="width" type="integer" use="required" />
		<attribute name="height" type="integer" use="required" />
	</complexType>

	<element name="layoutInfo">
		<complexType>
			<sequence>
				<element ref="tns:abstractLayoutInfo" />
			</sequence>
		</complexType>
	</element>

	<element name="labeledWidget" type="tns:tLabeledWidget"
		substitutionGroup="tns:widget" abstract="true" />

	<complexType name="tLabeledWidget">
		<complexContent>
			<extension base="tns:tWidget">
				<attribute name="label" type="string" />
			</extension>
		</complexContent>
	</complexType>

	<element name="button" type="tns:tButton" substitutionGroup="tns:labeledWidget" />

	<complexType name="tButton">
		<complexContent>
			<extension base="tns:tLabeledWidget"></extension>
		</complexContent>
	</complexType>

	<element name="link" type="tns:tLink" substitutionGroup="tns:labeledWidget" />

	<complexType name="tLink">
		<complexContent>
			<extension base="tns:tLabeledWidget"></extension>
		</complexContent>
	</complexType>

	<element name="label" type="tns:tLabel" substitutionGroup="tns:labeledWidget" />

	<complexType name="tLabel">
		<complexContent>
			<extension base="tns:tLabeledWidget"></extension>
		</complexContent>
	</complexType>

	<element name="image" type="tns:tImage" substitutionGroup="tns:widget" />

	<complexType name="tImage">
		<complexContent>
			<extension base="tns:tWidget" />
		</complexContent>
	</complexType>

	<element name="checkBox" type="tns:tCheckBox"
		substitutionGroup="tns:labeledWidget" />

	<complexType name="tCheckBox">
		<complexContent>
			<extension base="tns:tLabeledWidget" />
		</complexContent>
	</complexType>

	<element name="comboBox" type="tns:tComboBox"
		substitutionGroup="tns:labeledWidget" />

	<complexType name="tComboBox">
		<complexContent>
			<extension base="tns:tLabeledWidget">
				<attribute name="sampleData" type="string" />
			</extension>
		</complexContent>
	</complexType>

	<element name="radioButton" type="tns:tRadioButton"
		substitutionGroup="tns:labeledWidget" />

	<complexType name="tRadioButton">
		<complexContent>
			<extension base="tns:tLabeledWidget" />
		</complexContent>
	</complexType>

	<element name="list" type="tns:tList" substitutionGroup="tns:widget" />

	<complexType name="tList">
		<complexContent>
			<extension base="tns:tWidget">
				<attribute name="sampleData" type="string" />
			</extension>
		</complexContent>
	</complexType>

	<element name="textBox" type="tns:tTextBox" substitutionGroup="tns:widget" />

	<complexType name="tTextBox">
		<complexContent>
			<extension base="tns:tWidget">
				<attribute name="sampleData" type="string" />
			</extension>
		</complexContent>
	</complexType>

	<element name="textArea" type="tns:tTextArea" substitutionGroup="tns:widget" />

	<complexType name="tTextArea">
		<complexContent>
			<extension base="tns:tWidget">
				<attribute name="sampleData" type="string" />
			</extension>
		</complexContent>
	</complexType>

	<!-- COMPOSITE WIDGET -->
	<element name="compositeWidget" type="tns:tCompositeWidget"
		abstract="true" substitutionGroup="tns:widget" />

	<complexType name="tCompositeWidget">
		<complexContent>
			<extension base="tns:tWidget">
				<sequence>
					<sequence>
						<element ref="tns:layout" minOccurs="0" maxOccurs="1" />
						<element ref="tns:widgets" />
					</sequence>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<element name="widgets">
		<complexType>
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:widget" />
			</sequence>
		</complexType>
	</element>

	<element name="layout">
		<complexType>
			<sequence>
				<element ref="tns:abstractLayout" />
			</sequence>
		</complexType>
	</element>

	<element name="ui" type="tns:tUi" substitutionGroup="tns:compositeWidget" />

	<complexType name="tUi">
		<complexContent>
			<extension base="tns:tCompositeWidget">
				<attribute name="title" type="string" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<element name="panel" type="tns:tPanel" substitutionGroup="tns:compositeWidget" />

	<complexType name="tPanel">
		<complexContent>
			<extension base="tns:tCompositeWidget" />
		</complexContent>
	</complexType>

	<element name="repetition" type="tns:tRepetition"
		substitutionGroup="tns:compositeWidget" />

	<complexType name="tRepetition">
		<complexContent>
			<extension base="tns:tCompositeWidget" />
		</complexContent>
	</complexType>

	<!-- LAYOUT -->
	<element name="abstractLayout" type="tns:tLayout" abstract="true" />

	<complexType name="tLayout">

	</complexType>

	<element name="flowLayout" type="tns:tFlowLayout"
		substitutionGroup="tns:abstractLayout" />

	<complexType name="tFlowLayout">
		<complexContent>
			<extension base="tns:tLayout" />
		</complexContent>
	</complexType>

	<element name="linealLayout" type="tns:tLinealLayout"
		substitutionGroup="tns:abstractLayout" />

	<complexType name="tLinealLayout">
		<complexContent>
			<extension base="tns:tLayout">
				<attribute name="type">
					<simpleType>
						<restriction base="string">
							<enumeration value="vertical" />
							<enumeration value="horizontal" />
						</restriction>
					</simpleType>
				</attribute>
				<attribute name="boxes" type="integer" />
			</extension>
		</complexContent>
	</complexType>

	<element name="gridBagLayout" type="tns:tGridBagLayout"
		substitutionGroup="tns:abstractLayout" />

	<complexType name="tGridBagLayout">
		<complexContent>
			<extension base="tns:tLayout">
				<attribute name="columns" type="integer" use="required" />
				<attribute name="rows" type="integer" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<element name="absoluteLayout" type="tns:tGridBagLayout"
		substitutionGroup="tns:abstractLayout" />

	<complexType name="tAbsoluteLayout">

	</complexType>

	<!-- LAYOUT INFO -->
	<element name="abstractLayoutInfo" type="tns:tLayoutInfo"
		abstract="true" />

	<complexType name="tLayoutInfo">

	</complexType>

	<element name="linealLayoutInfo" type="tns:tLinealLayoutInfo"
		substitutionGroup="tns:abstractLayoutInfo" />

	<complexType name="tLinealLayoutInfo">
		<complexContent>
			<extension base="tns:tLayoutInfo">
				<attribute name="box" type="integer" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<element name="gridBoxLayoutInfo" type="tns:tGridBoxLayoutInfo"
		substitutionGroup="tns:abstractLayoutInfo" />

	<complexType name="tGridBoxLayoutInfo">
		<complexContent>
			<extension base="tns:tLayoutInfo">
				<attribute name="column" type="integer" use="required" />
				<attribute name="row" type="integer" use="required" />
				<attribute name="colspan" type="integer" default="1" />
				<attribute name="rowspan" type="integer" default="1" />
			</extension>
		</complexContent>
	</complexType>

	<element name="absoluteLayoutInfo" type="tns:tAbsoluteLayoutInfo"
		substitutionGroup="tns:abstractLayoutInfo" />

	<complexType name="tAbsoluteLayoutInfo">
		<complexContent>
			<extension base="tns:tLayoutInfo">
				<attribute name="x" type="integer" use="required" />
				<attribute name="y" type="integer" use="required" />
				<attribute name="width" type="integer" use="required" />
				<attribute name="height" type="integer" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<!-- TAGS -->

	<element name="tags">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element ref="tns:tag" />
			</sequence>
		</complexType>
	</element>

	<element name="tag">
		<complexType>
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element ref="tns:param" />
			</sequence>
			<attribute name="name" type="string" />
			<attribute name="tagSet" type="string" />
		</complexType>
	</element>

	<element name="param">
		<complexType>
			<attribute name="value" type="string" />
		</complexType>
	</element>
</schema>

=== estebanroblesluna/webspec-language/modules/webspeclanguage-mockupdd-core/src/test/resources/org/webspeclanguage/metamock/io/suiExample.xml
<mockups xmlns="http://www.webspeclanguage.org/sui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.webspeclanguage.org/sui sui.xsd ">
    <ui title="Login screen" id="loginScreen">
        <tags>
            <tag name="Node" tagSet="Nav">
                <param value="Login" />
            </tag>
            <tag name="Data" tagSet="Data">
                <param value="User" />
            </tag>
        </tags>
        <layout>
            <flowLayout />
        </layout>
        <widgets>
            <label id="usernameLabel" label="Username: ">
                <layoutInfo>
                    <gridBoxLayoutInfo column="1" row="1" />
                </layoutInfo>
                <originalPosition x="10" y="10" width="100" height="25" />
            </label>
            <textBox id="usernameTextbox">
                <layoutInfo>
                    <gridBoxLayoutInfo column="2" row="1" />
                </layoutInfo>
                <originalPosition x="125" y="10" width="100" height="25" />
            </textBox>
            <label id="passwordLabel" label="Password: ">
                <layoutInfo>
                    <gridBoxLayoutInfo column="1" row="2" />
                </layoutInfo>
                <originalPosition x="10" y="50" width="100" height="25" />
            </label>
            <textBox id="passwordTextbox">
                <layoutInfo>
                    <gridBoxLayoutInfo column="2" row="2" />
                </layoutInfo>
                <originalPosition x="125" y="50" width="100" height="25" />
            </textBox>
            <panel id="loginPanel">
                <originalPosition x="10" y="65" width="200" height="50" />
                <layout>
                    <flowLayout />
                </layout>
                <widgets>
                    <button id="loginButton" label="Login">
                        <originalPosition x="20" y="80" width="50" height="25" />
                    </button>
                    <checkBox id="rememberMeCheckbox" label="Remember me on this computer">
                        <originalPosition x="20" y="95" width="100" height="25" />
                    </checkBox>
                </widgets>
            </panel>
            <panel id="loginType">
                <originalPosition x="10" y="110" width="100" height="100" />
                <layout>
                    <flowLayout />
                </layout>
                <widgets>
                    <image id="loginBanner">
                        <originalPosition x="20" y="160" width="80" height="30" />
                    </image>
                    <radioButton id="normalLogin" label="Normal login">
                        <originalPosition x="20" y="120" width="80" height="30" />
                    </radioButton>
                    <radioButton id="facebookLogin" label="Facebook login">
                        <originalPosition x="20" y="160" width="80" height="30" />
                    </radioButton>
                    <comboBox id="loginAs">
                        <originalPosition x="30" y="240" width="200" height="200" />
                    </comboBox>
                </widgets>
            </panel>
            <repetition id="newsIndex">
                <originalPosition x="10" y="200" width="100" height="200" />
                <layout>
                    <flowLayout />
                </layout>
                <widgets>
                    <link id="newsLink" label="Some news">
                        <originalPosition x="20" y="210" width="80" height="30" />
                    </link>
                </widgets>
            </repetition>
        </widgets>
    </ui>
</mockups>
